package:
    type:           yii2-extension
    name:           hisite-module-news
    title:          HiSite News Module
    keywords:       hisite, module, news
    headline:       HiSite News
    namespace:      hisite\modules\news
    description:    |
        News module.
